version: '3'
services:
  mongodb:
    container_name: "mongodb"
    image: tonyh308/cv-mongodb:1
    build: ./mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INTIDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo/mongodb:/data/db
    ports:
      - 27017-27019:27017-27019
    labels:
      com.qa.description: "MongoDb Container for application."

  cv-react:
    container_name: "cv-react"
    image: tonyh308/cv-react:1.2.1
    build: ./frontend
    container_name: cv-react
    labels:
      com.qa.description: "ReactJS container application."
    ports:
      - 3000:3000
    depends_on:
      - cv-backend
    environment:
      - CI=true

  cv-backend:
    container_name: "cv-backend"
    image: tonyh308/cv-backend:test
    build: ./backend
    container_name: cv-backend
    labels:
      com.qa.description: "Spring-Boot REST API for application."
    environment:
      TZ: "Europe/London"
    volumes: 
      - /tmp
    depends_on:
      - mongodb
    ports:
      - 8081:8081
