version: '3'
services:
  mongodb:
    container_name: "mongodb"
    build: ./mongo
    image: mongodb
    labels:
      com.qa.description: "MongoDb Container for application."
    volumes:
      - ./mongo/mongodb:/data/db
    ports:
      - 27017:27017

  cv-react:
    container_name: "cv-react"
    build: ./frontend
    image: cv-react
    ports:
      - 3000:3000
    depends_on:
      - cv-backend
    environment:
      - CI=true

  cv-backend:
    container_name: "cv-backend"
    build: ./backend
    image: cv-backend
    volumes: 
      - /tmp
    depends_on:
      - mongodb
    ports:
      - 8081:8081

