name: Node.js CI

on:
  push: 
    branches: [developer, testing, frontend-testing]
  pull_request: 
    branches: [developer, testing, frontend-testing]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:  [10.x, 11.x, 12.x, 13.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        cd ./frontend
        npm install
        npm run build --if-present
        npm run jest
      env:
        CI: true

    - name: Cache files
      uses: actions/cache@v2.0.0
      with:
        path: 
          ./frontend/node_modules
          ./frontend/package*.json
        key:  ${{ matrix.node-version }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: | 
          ${{ matrix.node-version }}-node-${{ hashFiles('**/package.json') }} 
